spring.application.name=CollabXSkill
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8081}
spring.app.jwtSecret=${JWT_SECRET_KEY}
spring.app.jwtExpirationMs=9000000
spring.app.jwtRefreshMs=604800000
spring.ecom.app.jwtCookieName=springBootEcom
security.cookie.access-max-age=900
security.cookie.refresh-max-age=604800

#need to set the email and pass in env variable after creating app pass and then use it here like this
collab.admin.email=${YOUR_EMAIL}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${YOUR_EMAIL}
spring.mail.password=${YOUR_EMAIL_PASS}
#so i have to set the pass and email property in env variable after creating App pass and then use it here like this
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#TODO: so i have to change the path from relative to absolute because image not save in my  storage
file.upload-dir=/tmp/uploads

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

app.websocket.url=${WEBSOCKET_URL}