spring.application.name=CollabXSkill
spring.datasource.url=jdbc:postgresql://localhost:5432/collab_skill
spring.datasource.username=postgres
spring.datasource.password=postgreempire3@

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=900000
spring.app.jwtRefreshMs=604800000
spring.ecom.app.jwtCookieName=springBootEcom
security.cookie.access-max-age=900
security.cookie.refresh-max-age=604800

#need to set the email and pass in env variable after creating app pass and then use it here like this
collab.admin.email=onlyaryanking@gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=onlyaryanking@gmail.com
spring.mail.password=edql mlzr tzky ykul
#so i have to set the pass and email property in env variable after creating App pass and then use it here like this
#spring.mail.username=${EMAIL_USERNAME}
#spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#TODO: so i have to change the path from relative to absolute because image not save in my  storage
file.upload-dir=uploads/profiles

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB